import os

image_directory = 'previews'

github_repo_url = 'https://github.com/andrewzn69/wallpapers/tree/main/'


def generate_readme(directory):
    readme_content = "# Wallpapers\n\n> [!NOTE]\n> This README is autogenerated. You may view it's source code [here](https://github.com/andrewzn69/wallpapers/tree/main/.github/workflows). I do not own these images. All credits belong to the respective artists.\n\n"
    files = os.listdir(directory)

    for file in files:
        if file.endswith('.png'):
            # create links
            file_name, file_extension = os.path.splitext(file)
            print(file_name)
            readme_content += f"[{file_name}]({github_repo_url}{file_name})\n"
            readme_content += f"![{file_name}]({directory}/{file})\n---\n"

    return readme_content


readme_content = generate_readme(image_directory)

with open('README.md', 'w') as readme_file:
    readme_file.write(readme_content)

print("README.md generated successfully.")
