name: Generate README

on:
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Google Fonts
        run: |
          wget -O Ubuntu.zip https://fonts.google.com/download?family=Ubuntu
          unzip -d ubuntu/ Ubuntu.zip
          mv ubuntu /usr/share/fonts
          fc-cache -fv
          fc-list | grep Ubuntu

      - name: Set up ImageMagick
        run: |
          sudo apt-get install -y imagemagick
        shell: bash

      - name: Run the script
        run: bash .github/workflows/generate-gallery.sh
